import Head from 'next/head'
import requests from '../utils/requests'
import Header from './components/Header'
import Nav from './components/Nav'
import Result from './components/Result'

export default function Home({results}) {
  console.log(results)
  return (
    <div>
      <Head>
        <title>Exdity</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Nav />
      <Result results={results} />
    </div>
  )
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;
  const request = await fetch(`https://api.themoviedb.org/3${requests[genre]?.url || requests.fetchTrending.url}`
  ).then (res => res.json());

  return {
    props: {
      results: request.results,
    }
  }
}